name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*" # production
  pull_request:
    branches: ["*"] # build-only

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.

      - name: Test
        run: go test -race -coverprofile=.testCoverage.txt ./...
        timeout-minutes: 5

      - name: Generate Coverage Report
        run: go tool cover -html=.testCoverage.txt -o coverage.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage.html

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: figure out if we can run golangci-lint without loading (private) mods
      - name: Setup for private go modules
        run: |
          echo "machine github.com login ${{ secrets.GH_TOKEN_FOR_PACKAGES }} password x-oauth-basic" >> ~/.netrc
          go env -w GOPRIVATE="github.com/u-next/*"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=2m0s

